### ISSUE TITLE
Access to MessageInfo.fields 

### ISSUE THREAD

**Issue by andrenth** [Rantanen/protofish#8]
Hello

Would you consider making the `fields` field in `MessageInfo` public, or proving a method to list the available fields and/or field numbers?

My use case is exporting a protobuf message for use in an embedded scripting language, so I need to iterate over its fields to export each value to the scripting engine.

I’m currently doing this with `fields` from `MesageValue`, but this can be incomplete is the message has fields with default values.

**Comment by Rantanen** [comment]
I'll try coming up with a solution for this on the upcoming week! I'm sure there's no reason to keep that private (or to avoid a method exposing the fields) - just didn't have a use case for that myself so missed it in the API.

Don't remember the structure off the top of my head so can't comment whether a pub field vs method makes more sense now.

**Comment by Rantanen** [comment]
Sorry, got busy over the week. Should be done now.

The `MessageInfo` has `iter_fields` method. I thought of exposing the `fields` field, but due to its `BTreeMap` data type and ties to the `fields_by_name` field, I wanted the option to change those data types in the future, the `iter_fields` should remain forward compatible.

(Ended up also incrementing the version from 0.4.x to 0.5.0 as there were some version compatibility breaking changes on the main branch.)

**Comment by andrenth** [comment]
Thanks!

**Comment by andrenth** [comment]
Hi

I think you forgot to merge the fields branch onto main.

**Comment by Rantanen** [comment]
Uh.. maybe. :x

Done now, published 0.5.1. This time it should actually have the changes too!

**Comment by andrenth** [comment]
Thanks again :)
